- name: Clone restarters.net repository
  become: yes
  become_user: "{{ ssh_user }}"
  git: >
    repo=git@github.com:TheRestartProject/restarters.net.git
    dest="{{ application_path }}"
    key_file="{{ github_keyfile }}"
    accept_hostkey=yes
    update=yes
    version="{{ version }}"

- name: Build and run docker services
  docker_service:
    project_src: "{{ application_path }}"
    build: yes
    state: present
    files:
      - "{{ deployment_env }}.yml"
